version: '3.6'
services:

  minio:
    image: "minio/minio:latest"
    restart: always
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecret
    volumes:
      - type: bind
        source: ./minio-data
        target: /data

  neo4j:
    image: "neo4j:4.0.5"
    restart: always
    command: "neo4j"
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - type: bind
        source: ./neo-data
        target: /data

  honeycomb-service:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    depends_on:
      - minio
      - neo4j
    environment:
      NODE_ENV: docker-compose
      ENV: local
      NEO_URI: neo4j://neo4j
    ports:
      - 4000:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
      - node-modules:/app/node_modules


  postgres:
    image: "wildflowerschools/docker-postgres:10.4-debian-v6"
    restart: always
    ports:
      - 5432:5432
    env_file:
        - post.env
    volumes:
      - type: bind
        source: /data/postgres-restore
        target: /var/lib/postgresql/data

volumes:
  node-modules:
